/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  INonfungibleTokenPositionDescriptor,
  INonfungibleTokenPositionDescriptorInterface,
} from "../INonfungibleTokenPositionDescriptor";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "int256",
        name: "priority",
        type: "int256",
      },
    ],
    name: "UpdateTokenRatioPriority",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "contract INonfungiblePositionManager",
        name: "positionManager",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "tokenURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class INonfungibleTokenPositionDescriptor__factory {
  static readonly abi = _abi;
  static createInterface(): INonfungibleTokenPositionDescriptorInterface {
    return new utils.Interface(
      _abi
    ) as INonfungibleTokenPositionDescriptorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): INonfungibleTokenPositionDescriptor {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as INonfungibleTokenPositionDescriptor;
  }
}
